apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-test-logs
spec:
  storageClassName: airflow-test-logs
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /finance/airflow-test/logs #更改为您想要的目录